from typing import Iterable, Protocol

from domain.entities.artist import Artist


class ArtistRepository(Protocol):
    async def get_by_oid(self, artist_oid: str) -> Artist | None: ...

    async def get_list(self, limit: int, offset: int) -> list[Artist]: ...

    async def get_total_count(self) -> int: ...

    async def filter_by_oids(self, artist_oids: Iterable[str]) -> list[Artist]: ...

    async def upsert(self, artist: Artist) -> None: ...
