import typing as tp
from domain.entities.playlist import Playlist


class PlaylistRepository(tp.Protocol):
    async def get_all(self, my_oid: str, limit: int) -> list[Playlist]: ...

    async def get_one(self, my_oid: str, playlist_oid: str) -> Playlist | None: ...

    async def save(self, playlist: Playlist) -> None: ...

    async def remove(self, my_oid: str, playlist_oid: str) -> None: ...
