from typing import Protocol

from domain.entities.artist import Artist
from domain.entities.track import Track


class TrackRepository(Protocol):
    async def get_by_oid(self, track_oid: str) -> Track | None: ...

    async def get_top_for_all_time(self, limit: int) -> list[Track]: ...

    async def get_top_for_day(self, limit: int) -> list[Track]: ...

    async def upsert(self, track: Track) -> None: ...

    async def set_track_artists(self, track_oid: str, *artists: Artist) -> None: ...

    async def increment_listens(self, track_oid: str) -> None: ...
