"""add listens_per_day column

Revision ID: 05700022dfdc
Revises: 01c253f58804
Create Date: 2024-08-04 13:13:37.711598

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05700022dfdc"
down_revision: Union[str, None] = "01c253f58804"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "track",
        sa.Column("listens_per_day", sa.Integer(), server_default="0", nullable=False),
    )
    op.alter_column(
        "track",
        "listens",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "track",
        "listens",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("track", "listens_per_day")
    # ### end Alembic commands ###
