"""created tables

Revision ID: 26e00fdb71e7
Revises: 
Create Date: 2024-07-31 16:09:25.029815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26e00fdb71e7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("cover_url", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "artist",
        sa.Column("nickname", sa.String(length=50), nullable=False),
        sa.Column("avatar_url", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("cover_url", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlist_user_id"), "playlist", ["user_id"], unique=False)
    op.create_table(
        "track",
        sa.Column("audio_url", sa.String(length=255), nullable=False),
        sa.Column("duration", sa.Numeric(precision=3, scale=0), nullable=False),
        sa.Column("album_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["album_id"], ["album.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("audio_url"),
    )
    op.create_table(
        "track_artist",
        sa.Column("artist_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("track_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.UniqueConstraint(
            "artist_id", "track_id", name="track_artist_unique_constraint"
        ),
    )
    op.create_table(
        "track_in_playlist",
        sa.Column("playlist_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("track_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.UniqueConstraint(
            "playlist_id", "track_id", name="track_in_playlist_unique_constraint"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_in_playlist")
    op.drop_table("track_artist")
    op.drop_table("track")
    op.drop_index(op.f("ix_playlist_user_id"), table_name="playlist")
    op.drop_table("playlist")
    op.drop_table("artist")
    op.drop_table("album")
    # ### end Alembic commands ###
