"""empty message

Revision ID: e9b7f4424dd2
Revises: a1f2e957fd6d
Create Date: 2024-09-29 23:52:30.517178

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9b7f4424dd2"
down_revision: Union[str, None] = "a1f2e957fd6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column(
            "type",
            sa.Enum("ACCESS_TOKEN", "REFRESH_TOKEN", name="tokentype"),
            nullable=False,
        ),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("expired_at > created_at"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token")
    # ### end Alembic commands ###
