"""empty message

Revision ID: d4bdb4f0e345
Revises: e9b7f4424dd2
Create Date: 2024-09-29 23:57:05.162863

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4bdb4f0e345"
down_revision: Union[str, None] = "e9b7f4424dd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("token", sa.Column("device_id", sa.String(length=255), nullable=False))
    op.add_column("token", sa.Column("is_revoked", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token", "is_revoked")
    op.drop_column("token", "device_id")
    # ### end Alembic commands ###
