"""empty message

Revision ID: a1f2e957fd6d
Revises: 
Create Date: 2024-09-29 22:56:48.023953

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1f2e957fd6d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("cover_url", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=70), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "artist",
        sa.Column("nickname", sa.String(length=50), nullable=False),
        sa.Column("avatar_url", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "otpcode",
        sa.Column("code", sa.Numeric(precision=4, scale=0), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column("purpose", sa.Enum("VERIFY", name="otpcodepurpose"), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "purpose", name="otp_code_unique_constraint"),
    )
    op.create_table(
        "playlist",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("cover_url", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlist_user_id"), "playlist", ["user_id"], unique=False)
    op.create_table(
        "track",
        sa.Column("audio_url", sa.String(length=255), nullable=False),
        sa.Column("duration", sa.Numeric(precision=3, scale=0), nullable=False),
        sa.Column("album_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["album_id"], ["album.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("audio_url"),
    )
    op.create_table(
        "listener",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column(
            "last_listened_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint("user_id", "track_id", name="listener_unique_constraint"),
    )
    op.create_table(
        "track_artist",
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.UniqueConstraint(
            "artist_id", "track_id", name="track_artist_unique_constraint"
        ),
    )
    op.create_table(
        "track_in_playlist",
        sa.Column("playlist_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.UniqueConstraint(
            "playlist_id", "track_id", name="track_in_playlist_unique_constraint"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_in_playlist")
    op.drop_table("track_artist")
    op.drop_table("listener")
    op.drop_table("track")
    op.drop_index(op.f("ix_playlist_user_id"), table_name="playlist")
    op.drop_table("playlist")
    op.drop_table("otpcode")
    op.drop_table("artist")
    op.drop_table("user")
    op.drop_table("album")
    # ### end Alembic commands ###
